# Generated by Django 5.1 on 2024-09-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_skill_options_skill_skill_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
